### ISSUE TITLE
TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by fpcarva** [Minyall/gephi_twitter_media_downloader#14]
I run the code today and this problem appears, what I need to do to resolve this?

Traceback (most recent call last):
  File "C:\Users\projf\projetos\gephi_twitter_media_downloader-master\download_twitter_media.py", line 153, in <module>
    main()
  File "C:\Users\projf\projetos\gephi_twitter_media_downloader-master\download_twitter_media.py", line 119, in main
    data_dict['original_row'] = indexes[i] +2
TypeError: 'str' object does not support item assignment

**Comment by fpcarva** [comment]
I'm saving a CSV with IDs with pandas. The class of element of column is <class 'numpy.int64'>. So, supposedly it would not be read as a 'str' in the code, however I am receiving this error. When I manually set the tweet ids I don't recive this error. The code understand this like not str. But, in my case I need to use python to create the csv. What can I do to solve this?  Thank You very much

**Comment by fpcarva** [comment]
I solve the problem!
